import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'getting-started/index'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Learn',
      link: {
        type: 'generated-index',
        description: 'Choose a learning path that matches your experience level.',
      },
      items: [
        {
          type: 'category',
          label: 'Beginner Course',
          link: {
            type: 'generated-index',
            description: 'A step-by-step course for Sui beginners.',
          },
          items: [{type: 'autogenerated', dirName: 'learn/beginner'}],
        },
        {
          type: 'category',
          label: 'Advanced Course',
          link: {
            type: 'generated-index',
            description: 'Advanced topics for experienced Sui developers.',
          },
          items: [{type: 'autogenerated', dirName: 'learn/advanced'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Live Code Example',
      items: [{type: 'autogenerated', dirName: 'live-code-example'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
