import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually define top-level ordering (while keeping folders auto-generated inside)
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Beginner Course',
      items: [{type: 'autogenerated', dirName: 'beginner'}],
    },
    {
      type: 'category',
      label: 'Live Code Example',
      items: [{type: 'autogenerated', dirName: 'live-code-example'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
